### ISSUE TITLE
Missing methods in BufferManager.cs

### ISSUE THREAD

**Issue by thePostFuturist** [dr-matt-smith/SSULK#1]
`Assets\SSULK\server_unity\Assets\_Scripts\SocketServer\Server4.cs(290,42): error CS1061: 'BufferManager' does not contain a definition for 'GetMessageInBuffer' and no accessible extension method 'GetMessageInBuffer' accepting a first argument of type 'BufferManager' could be found (are you missing a using directive or an assembly reference?)
`

Which makes sense, considering BufferManager.cs does not have GetMessageInBuffer method. BufferHelper.cs does, but nothing is invoking it.

Unity 2018.3, .NET 4.x

**Comment by dr-matt-smith** [comment]
fixed by replacing references to `m_bufferManager` by reference to new property instance of `BufferHelper` named `m_bufferHelper`
